Creating remaining classes and Create the associations between them
bienvenuushindi/school-library pull request #4
Opened 2022-09-28 15:22 UTC by bienvenuushindi

# Requirements :recycle: 
- [ ] Create a class Classroom
- [ ] Create the has-many/belongs-to relationship between Classroom and Student
- [ ] Create a class Book
- [ ] Create a class Rental
- [ ] Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental

2022-09-28 16:36 UTC, Munsa1 requested changes
Hi @bienvenuushindi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 16:36 UTC, Munsa1 commented on association/classroom.rb
> +  end
- [ ] Kindly implement the method that serves as the 'has-many' (a classroom has many students). like the foloowing example
![image](https://user-images.githubusercontent.com/81932478/192830153-421dc299-8961-45d6-874c-564e166668eb.png)

2022-09-28 16:36 UTC, Munsa1 commented on classes/student.rb
>      @classroom = classroom
- [ ] It is a requirement that When setting the classroom for a student it also adds it to the classrooms' students:
e.g
``classroom.students.push(self) unless classroom.students.include?(self)``

2022-09-28 16:36 UTC, Munsa1 commented on classes/person.rb
> +  end
- [ ] The add_rental method shpuld be implemented as follows, so as to achieve the has-many association.
![image](https://user-images.githubusercontent.com/81932478/192837502-e1cbf12b-9b58-421d-8e03-d05ded5177aa.png)

2022-09-29 12:45 UTC, Wes-Isaac requested changes
Hi @bienvenuushindi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
- No linter error ✅.
- Great PR description 👍.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-29 12:45 UTC, Wes-Isaac commented on classes/person.rb
> +  end
- [ ] Great job so far, in order to achieve the` has-many` association the person itself needs to be sent. Kindly fix that.

`i.e  Rental.new(....)`

2022-09-29 13:46 UTC, m05e5 approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @bienvenuushindi   🔥 

Good job on implementing the required changes. You smashed it. Well Done.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


Now you can merge this branch 🚀 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 13:48 UTC, merged